/*
028-[프로그래머스]-JOIN-복습필요(특정-기간동안-대여-가능한-자동차들의-대여비용-구하기)-LV4-(1-다른풀이-참고).sql

### 주소
> https://school.programmers.co.kr/learn/courses/30/lessons/157339

### 참고
> https://velog.io/@greaceh/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-SQL-%ED%8A%B9%EC%A0%95-%EA%B8%B0%EA%B0%84%EB%8F%99%EC%95%88-%EB%8C%80%EC%97%AC-%EA%B0%80%EB%8A%A5%ED%95%9C-%EC%9E%90%EB%8F%99%EC%B0%A8%EB%93%A4%EC%9D%98-%EB%8C%80%EC%97%AC%EB%B9%84%EC%9A%A9-%EA%B5%AC%ED%95%98%EA%B8%B0

*** 11:15~:11:56
### 내 설계 분, 총 분
> 테이블 지정
    - CAR_RENTAL_COMPANY_CAR C / CAR_RENTAL_COMPANY_RENTAL_HISTORY H / CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
> 조회
    - C.CAR_ID / C.CAR_TYPE / (C.DAILY_FEE * P.DISCOUNT_RATE * 30) AS FEE
> 조인
    - CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
> 조건(WHERE)
    - 자동차 = 세단 또는 SUV
        - C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV'
        - FEE BETWEEN 500000 AND 2000000
        - 기간 > ???
> 정렬
    - FEE DESC / C.CAR_TYPE ASC / C.CAR_ID DESC

### 참고
>>> '2022년 11월 1일부터 2022년 11월 30일까지 대여 가능'하다는 조건이 조금 힘들었다/

*/

-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID=H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND P.DURATION_TYPE='30일 이상'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;